// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwUA4FZ0YO_jsvnFayRN5L_Ku8zDOaPQ',
    appId: '1:188971643704:web:3fa2e94a35305ea44b07cd',
    messagingSenderId: '188971643704',
    projectId: 'hw04-9e193',
    authDomain: 'hw04-9e193.firebaseapp.com',
    storageBucket: 'hw04-9e193.firebasestorage.app',
    measurementId: 'G-QHD87J93G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTANqeMplMA0hAZcl0OU3njexKizkwtY',
    appId: '1:188971643704:android:16b5c8e75ec95e2e4b07cd',
    messagingSenderId: '188971643704',
    projectId: 'hw04-9e193',
    storageBucket: 'hw04-9e193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbHoYDk3v0tDLH0IRfRTX4X1bmFC5TBM',
    appId: '1:188971643704:ios:024aff1fec2bd4324b07cd',
    messagingSenderId: '188971643704',
    projectId: 'hw04-9e193',
    storageBucket: 'hw04-9e193.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkbHoYDk3v0tDLH0IRfRTX4X1bmFC5TBM',
    appId: '1:188971643704:ios:024aff1fec2bd4324b07cd',
    messagingSenderId: '188971643704',
    projectId: 'hw04-9e193',
    storageBucket: 'hw04-9e193.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjwUA4FZ0YO_jsvnFayRN5L_Ku8zDOaPQ',
    appId: '1:188971643704:web:b88bb9add5e3fd8c4b07cd',
    messagingSenderId: '188971643704',
    projectId: 'hw04-9e193',
    authDomain: 'hw04-9e193.firebaseapp.com',
    storageBucket: 'hw04-9e193.firebasestorage.app',
    measurementId: 'G-Y27K6NQWKQ',
  );
}


